language: node_js
branches:
  only:
  - master
before_script: npm install -g grunt-cli
script: grunt build-prod
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
  bucket: www.taylorgriggs.com
  acl: public_read
  region: us-east-1
  detect_encoding: true
  skip_cleanup: true
  local_dir: dist
  on:
    repo: gleung93/griggsPortfolio
